### PR TITLE
Update harbour-wunderfitz-es.ts

### PR DESCRIPTION
**Pull request by carlosgonzz**
now full translated : )

### CODE REVIEW

**Comment by carlosgonzz** [comment]
hello, are you accepting translation from here?

**Comment by Wunderfitz** [comment]
Yes, of course. Sorry - was so busy that I didn't see it.

However, please wait a bit with the translation. There are so many changes at the moment, that you probably waste precious time... I'll let you know when it's more or less final.

**Comment by Wunderfitz** [comment]
Hi there,

merged your changes, thanks again. I plan to release it pretty soon... There are a lot of new strings, but don't bother yourself too much with all the things... I guess, most of the stuff can remain in English, especially on the RegistrationPage and the languages which are supported by the Beta OCR feature.

**Comment by Wunderfitz** [comment]
BTW, if you want a preview version to check how it looks like, please send me an e-mail - you'll get a link. :)

**Comment by carlosgonzz** [comment]
carlosgonz@protonmail.com 
I will continue translating after I get the preview-app for a better translation.
Thanks

**Comment by Wunderfitz** [comment]
You have mail! :)

**Pull request merged**
